### ISSUE TITLE
linux installer

### ISSUE THREAD

**Issue by trstdm** [Holic75/Baldurs-gate-dnd-3.5#2]
any love for linux? or a how-to for linux manual installation?

lots of love for the awesome work <3

**Comment by Holic75** [comment]
you could probably try to install it using wine, but the issue is that there are plenty of small files which wine does not like and installation process might take few hours ...

**Comment by trstdm** [comment]
Yeah, i thought of that a few moments after posting, it's still going... and i'm getting Errors when converting items

ERROR: cannot convert strname or "strname" to integer

It's on a clean, fresh, steam install, i'll post more details tomorrow

**Comment by Holic75** [comment]
errors are ok, they are for debug purposes only,

**Comment by trstdm** [comment]
Oh, good to know :) i don't know how bg modding works, is it possible to do it on windows and just copy override folder to linux?

**Comment by Holic75** [comment]
probably, the only issue is that filenames in windows are case insensitive, while on linux they do not, so you will likely need to change their names in override folder to uppercase, you will also need to copy corresponding dialog.tlk

**Comment by trstdm** [comment]
wellp, after waiting 6 hours on Spell DC update I simply cancelled it. Will give it a try by moving files from windows installation.
