### ISSUE TITLE
Armor max dex not working? 

### ISSUE THREAD

**Issue by peren717** [Holic75/Baldurs-gate-dnd-3.5#3]

**Comment by Holic75** [comment]
Could you provide a more elaborate description on what does not work, what  you expect, post mod and game version, item that fails, and probably some screenshots?

**Comment by FeronSchneider** [comment]
Same issue.

I'm using a heavy plate  armor (Max dex 0) and still have DEX bonus on AC.

By the way. GREAT mod. It's like a dream. =]

**Comment by Holic75** [comment]
Can you state the mod/game version as well as post your weidu log and a save game with corresponding issue?

**Comment by Holic75** [comment]
Also please check carefully that you indeed get the dex bonus (it will be written on your character sheet that you indeed get dex bonus, but after ~ 1 second after you equip armor you should get an AC penalty removing the corresponding amount of dex bonus)

**Comment by FeronSchneider** [comment]
Well, I understand now. When the mod check for spell failure (I imagine now, it's not the only thing that mod check) there is a update in the all bonus.

Anyway, just need wait for some seconds and all is ok.

Thanks for reply!

**Comment by FeronSchneider** [comment]
Oh! I seeing your answer now! Thanks.
