### ISSUE TITLE
Scroll Bar Button. Jump Up

### ISSUE THREAD

**Issue by FeronSchneider** [Holic75/Baldurs-gate-dnd-3.5#4]
Always when I'm opening an inventory, conteiner. etc the dialog box scroll bar jump to top.

And the dialog box doesn't keep up with with the new info (Voices, combat roll, etc)

**Comment by Holic75** [comment]
Can you tell me the game, version and platform and confirm that this issue does not appear without mod installed?

**Comment by Holic75** [comment]
Are you playing BG2 2.5?   I think it might be related to it. I'm using 2.3 and   do not have any issues.

**Comment by FeronSchneider** [comment]
Yes. 2.5

So, that is.

**Comment by FeronSchneider** [comment]
Solved!
