### ISSUE TITLE
Other languages compatibility

### ISSUE THREAD

**Issue by Majber** [Holic75/Baldurs-gate-dnd-3.5#7]
Do you think that your mod should/can be compatible with other languages?

**Comment by Holic75** [comment]
Yes it could, but I'm not sure I will ever work on it. To estimate amount of translation work you can check files in 3ed/tra folder.

**Comment by Majber** [comment]
I dont have problem with partly english (from your mod). I just want to install it over polish version (becouse I prefer polish audio for BG2) , I hope it will not break the game. I will report back after testing this.

**Comment by Holic75** [comment]
No, it will not work, because it uses some string look up and assumes that
they are in english.

**Comment by Jc2486** [comment]
Since Majber only want the Polish audio, is it possible for him to rename Polish audio to English version names and just install the English version?

**Comment by Majber** [comment]
I forgot to report back:
During installation of mod I picked polish version. 
Now after installation I have polish audio, and mix of polish and english letters (for new things that were added in mod) and its exacly what I want. 
So far no bugs or nothing weird with mixing.
